[tool.poetry]
name = "bittrade-kraken-rest"
version = "0.1.0"
description = ""
authors = ["mat <matt@techspace.asia>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
rich = "^12.6.0"
fire = "^0.4.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
